packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "aws_source_ami" {
  type    = string
  default = "ami-039a49e70ea773ffc"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" { # while converting from JSON to HCL then it will rename the source block to autogenerated_1 over here as in JSON there were nothing call source block
  ami_name      = "tmp-${local.timestamp}"# here the ami_name been pulled in the local variable that been defined out in here 
  instance_type = "t2.micro"
  region        = "us-east-1"
  source_ami    = "${var.aws_source_ami}" # here this source_ami been refered from the variable block that we have defined earlier
  ssh_pty       = true
  ssh_username  = "ubuntu"
  tags = {
    Created-by = "Packer"
    OS_Version = "Ubuntu"
    Release    = "Latest"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"] # here referecing the source block from build block here

  provisioner "shell" {
    inline = ["mkdir ~/src", "cd ~/src", "git clone https://github.com/hashicorp/demo-terraform-101.git", "cp -R ~/src/demo-terraform-101/assets /tmp", "sudo sh /tmp/assets/setup-web.sh"]
  }

}
